# Hey Emacs, this is a -*- makefile -*-

#############################

MAIN_FILE := timer0_pwm
SOURCES := $(MAIN_FILE).c

#############################
# Não modifique a linha abaixo

include Makefile_base
