# Hey Emacs, this is a -*- makefile -*-

#############################

MAIN_FILE := int0_simples
SOURCES := $(MAIN_FILE).c

#############################
# Não modifique a linha abaixo

include Makefile_base
